### ISSUE TITLE
why are you using a tuple input?

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/giocomo-lab-to-nwb#1]
https://github.com/ben-dichter-consulting/giocomo-lab-to-nwb/blob/9a20563c265d9cfbdf726b2920f6823151b1979f/giocomo-lab-to-nwb/conversion.py#L10-L38

**Comment by bendichter** [comment]
should be:

```python
def convert(input_file, subject_id, subject_dob, ...):
```

**Comment by kristinquick** [comment]
I thought it was cleaner to have a single output from my `def buttonRun(self):` in `interface_giu.py` was cleaner than all separate variables.  What is the motivation behind having all the variables separated?  Just curious so I can do it the right way next time.

**Comment by bendichter** [comment]
The way it is written it is difficult to tell what the argument order is supposed to be. Please use a numpy docstring to document each function

**Comment by bendichter** [comment]
You can have a single output and then unpack them when you call `convert` with `convert(*button_run_output_tuple)`

**Comment by kristinquick** [comment]
I unpacked the tuple from `interface_gui.py` and added doc string
