### ISSUE TITLE
datetimes

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/giocomo-lab-to-nwb#2]
datetimes need to be in ISO 8601. pynwb can convert it for you if you input a `datetime` object. A string field won't work. You'll need to use something like https://pypi.org/project/tkcalendar/.

**Comment by kristinquick** [comment]
This is cool, thanks.  I'll implement this.

**Comment by kristinquick** [comment]
Converted to `datetime` objects and used tkcalendar
